-- MySQL Script generated by MySQL Workbench
-- Mon Feb 14 03:17:35 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema minidebtbook
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema minidebtbook
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `minidebtbook` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `minidebtbook` ;

-- -----------------------------------------------------
-- Table `minidebtbook`.`currency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minidebtbook`.`currency` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(20) NOT NULL,
  `Abbrev` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `minidebtbook`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minidebtbook`.`customer` (
  `CustomerID` INT NOT NULL,
  `Name` VARCHAR(50) NOT NULL,
  `Type` INT NOT NULL,
  `Phone` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `minidebtbook`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minidebtbook`.`account` (
  `ID` INT NOT NULL,
  `CustomerID` INT NOT NULL,
  `CurrencyID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Account_CustomerID` (`CustomerID` ASC) VISIBLE,
  INDEX `fk_Account_CurrencyID` (`CurrencyID` ASC) VISIBLE,
  CONSTRAINT `fk_Account_CurrencyID`
    FOREIGN KEY (`CurrencyID`)
    REFERENCES `minidebtbook`.`currency` (`ID`),
  CONSTRAINT `fk_Account_CustomerID`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `minidebtbook`.`customer` (`CustomerID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `minidebtbook`.`document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minidebtbook`.`document` (
  `DocID` INT NOT NULL,
  `Type` INT NOT NULL,
  `CustomerID` INT NOT NULL,
  `CurrencyID` INT NOT NULL,
  `Date` DATE NOT NULL,
  PRIMARY KEY (`DocID`),
  INDEX `fk_Document_CustomerID` (`CustomerID` ASC) VISIBLE,
  INDEX `fk_Document_CurrencyID` (`CurrencyID` ASC) VISIBLE,
  CONSTRAINT `fk_Document_CurrencyID`
    FOREIGN KEY (`CurrencyID`)
    REFERENCES `minidebtbook`.`currency` (`ID`),
  CONSTRAINT `fk_Document_CustomerID`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `minidebtbook`.`customer` (`CustomerID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `minidebtbook`.`account_line`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minidebtbook`.`account_line` (
  `ID` INT NOT NULL,
  `CustomerID` INT NOT NULL,
  `Type` INT NOT NULL,
  `Amount` INT NOT NULL,
  `Date` DATE NOT NULL,
  `DocID` INT NOT NULL,
  `Details` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Account_line_DocID` (`DocID` ASC) VISIBLE,
  CONSTRAINT `fk_Account_line_DocID`
    FOREIGN KEY (`DocID`)
    REFERENCES `minidebtbook`.`document` (`DocID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `minidebtbook`.`bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minidebtbook`.`bill` (
  `BillID` INT NOT NULL,
  `Amount_Delivered` INT NOT NULL,
  `DocID` INT NOT NULL,
  PRIMARY KEY (`DocID`),
  UNIQUE INDEX `uc_Bill_BillID` (`BillID` ASC) VISIBLE,
  CONSTRAINT `fk_Bill_DocID`
    FOREIGN KEY (`DocID`)
    REFERENCES `minidebtbook`.`document` (`DocID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `minidebtbook`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minidebtbook`.`category` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(20) NOT NULL,
  `Abbrev` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `minidebtbook`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minidebtbook`.`item` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(50) NOT NULL,
  `Price` INT NOT NULL,
  `CategoryID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `uc_Item_Name` (`Name` ASC) VISIBLE,
  INDEX `fk_Item_CategoryID` (`CategoryID` ASC) VISIBLE,
  CONSTRAINT `fk_Item_CategoryID`
    FOREIGN KEY (`CategoryID`)
    REFERENCES `minidebtbook`.`category` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `minidebtbook`.`bill_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minidebtbook`.`bill_item` (
  `ItemID` INT NOT NULL,
  `BillID` INT NOT NULL,
  `Quantity` INT NOT NULL,
  PRIMARY KEY (`ItemID`, `BillID`),
  INDEX `fk_Bill_Item_BillID` (`BillID` ASC) VISIBLE,
  CONSTRAINT `fk_Bill_Item_BillID`
    FOREIGN KEY (`BillID`)
    REFERENCES `minidebtbook`.`bill` (`BillID`),
  CONSTRAINT `fk_Bill_Item_ItemID`
    FOREIGN KEY (`ItemID`)
    REFERENCES `minidebtbook`.`item` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `minidebtbook`.`income_fund`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minidebtbook`.`income_fund` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(20) NOT NULL,
  `CurrencyID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Income_fund_CurrencyID` (`CurrencyID` ASC) VISIBLE,
  CONSTRAINT `fk_Income_fund_CurrencyID`
    FOREIGN KEY (`CurrencyID`)
    REFERENCES `minidebtbook`.`currency` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `minidebtbook`.`receipt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minidebtbook`.`receipt` (
  `ReceiptID` INT NOT NULL,
  `Type` INT NOT NULL,
  `Amount` INT NOT NULL,
  `DocID` INT NOT NULL,
  PRIMARY KEY (`DocID`),
  UNIQUE INDEX `uc_Receipt_ReceiptID` (`ReceiptID` ASC) VISIBLE,
  CONSTRAINT `fk_Receipt_DocID`
    FOREIGN KEY (`DocID`)
    REFERENCES `minidebtbook`.`document` (`DocID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
